apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "mlops-search.name" . }}
  labels:
    {{- include "mlops-search.labels" . | nindent 4 }}
data:
  SERVICE_NAME: "runbook-search-api"
  APP_VERSION: {{ .Chart.AppVersion | quote }}
  BUILD_REVISION: {{ .Values.buildRevision | quote }}
  ENVIRONMENT: {{ .Values.environment | quote }}
  RANKING_MODE: {{ .Values.rankingMode | quote }}
  IMAGE_DIGEST: {{ required "image.digest is required" .Values.image.digest | quote }}
